"""Classification-family prompt exports."""

from case_generator.prompts.clasificacion.M1_clasificacion import (
    CASE_ARCHITECT_PROMPT_CLASSIFICATION,
    CASE_QUESTIONS_PROMPT_CLASSIFICATION,
    CASE_WRITER_PROMPT_CLASSIFICATION,
)
from case_generator.prompts.clasificacion.dataset import (
    SCHEMA_DESIGNER_PROMPT_CLASSIFICATION,
)
from case_generator.prompts.clasificacion.narrative import (
    M3_CONTENT_PROMPT_CLASSIFICATION,
    M3_CONTENT_PROMPT_CLASSIFICATION_BY_VARIANT,
    M3_CONTENT_PROMPT_CLASSIFICATION_LR_ONLY,
    M3_CONTENT_PROMPT_CLASSIFICATION_RF_ONLY,
    M4_PROMPT_CLASSIFICATION,
    M5_PROMPT_CLASSIFICATION,
)
from case_generator.prompts.clasificacion.notebook import (
    M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION,
)
from case_generator.prompts.clasificacion.notebooks import (
    CLASSIFICATION_NOTEBOOK_PROMPT_BY_VARIANT,
    CLASSIFICATION_NOTEBOOK_VARIANT_LR_ONLY,
    CLASSIFICATION_NOTEBOOK_VARIANT_LR_RF_CONTRAST,
    CLASSIFICATION_NOTEBOOK_VARIANT_RF_ONLY,
    ClassificationNotebookVariant,
    M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_LR_ONLY,
    M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_LR_RF_CONTRAST,
    M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_RF_ONLY,
)

__all__ = [
    "CASE_ARCHITECT_PROMPT_CLASSIFICATION",
    "CASE_WRITER_PROMPT_CLASSIFICATION",
    "CASE_QUESTIONS_PROMPT_CLASSIFICATION",
    "SCHEMA_DESIGNER_PROMPT_CLASSIFICATION",
    "M3_CONTENT_PROMPT_CLASSIFICATION",
    "M3_CONTENT_PROMPT_CLASSIFICATION_LR_ONLY",
    "M3_CONTENT_PROMPT_CLASSIFICATION_RF_ONLY",
    "M3_CONTENT_PROMPT_CLASSIFICATION_BY_VARIANT",
    "M4_PROMPT_CLASSIFICATION",
    "M5_PROMPT_CLASSIFICATION",
    "M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION",
    "M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_LR_ONLY",
    "M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_RF_ONLY",
    "M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_LR_RF_CONTRAST",
    "CLASSIFICATION_NOTEBOOK_PROMPT_BY_VARIANT",
    "CLASSIFICATION_NOTEBOOK_VARIANT_LR_ONLY",
    "CLASSIFICATION_NOTEBOOK_VARIANT_RF_ONLY",
    "CLASSIFICATION_NOTEBOOK_VARIANT_LR_RF_CONTRAST",
    "ClassificationNotebookVariant",
]
