"""Classification-family prompt exports."""

from case_generator.prompts.clasificacion.M1_clasificacion import (
    CASE_ARCHITECT_PROMPT_CLASSIFICATION,
    CASE_QUESTIONS_PROMPT_CLASSIFICATION,
    CASE_WRITER_PROMPT_CLASSIFICATION,
    M1_CLASSIFICATION_BUSINESS_TARGET_BLOCK,
    build_cost_matrix_block,
)
from case_generator.prompts.clasificacion.M2_clasificacion import (
    EDA_ANNOTATE_ONLY_PROMPT_CLASSIFICATION,
    EDA_QUESTIONS_GENERATOR_PROMPT_CLASSIFICATION,
    EDA_TEXT_ANALYST_PROMPT_CLASSIFICATION,
    SCHEMA_DESIGNER_PROMPT_CLASSIFICATION,
    select_eda_text_blocks,
)
from case_generator.prompts.clasificacion.M3_clasificacion.content import (
    M3_CONTENT_PROMPT_CLASSIFICATION,
    M3_CONTENT_PROMPT_CLASSIFICATION_BY_VARIANT,
    M3_CONTENT_PROMPT_CLASSIFICATION_LR_ONLY,
    M3_CONTENT_PROMPT_CLASSIFICATION_RF_ONLY,
)
from case_generator.prompts.clasificacion.M3_clasificacion.notebook_questions import (
    M3_NOTEBOOK_QUESTIONS_PROMPT_CLASSIFICATION_BY_VARIANT,
    M3_NOTEBOOK_QUESTIONS_PROMPT_CLASSIFICATION_LR_ONLY,
    M3_NOTEBOOK_QUESTIONS_PROMPT_CLASSIFICATION_RF_ONLY,
)
from case_generator.prompts.clasificacion.M3_clasificacion.questions import (
    M3_CLASSIFICATION_QUESTIONS_BY_VARIANT,
    M3_CLASSIFICATION_QUESTIONS_PROMPT_LR_ONLY,
    M3_CLASSIFICATION_QUESTIONS_PROMPT_LR_RF_CONTRAST,
    M3_CLASSIFICATION_QUESTIONS_PROMPT_RF_ONLY,
)
from case_generator.prompts.clasificacion.M4_clasificacion import (
    M4_CHART_PROMPT_CLASSIFICATION,
    M4_CHART_PROMPT_CLASSIFICATION_LEGACY,
    M4_NARRATIVE_PROMPT_CLASSIFICATION,
    M4_NARRATIVE_PROMPT_CLASSIFICATION_BY_VARIANT,
    M4_NARRATIVE_PROMPT_CLASSIFICATION_LR_ONLY,
    M4_NARRATIVE_PROMPT_CLASSIFICATION_RF_ONLY,
    M4_QUESTIONS_PROMPT_CLASSIFICATION,
)
from case_generator.prompts.clasificacion.M5_clasificacion import (
    M5_NARRATIVE_PROMPT_CLASSIFICATION,
    M5_NARRATIVE_PROMPT_CLASSIFICATION_BY_VARIANT,
    M5_NARRATIVE_PROMPT_CLASSIFICATION_LR_ONLY,
    M5_NARRATIVE_PROMPT_CLASSIFICATION_RF_ONLY,
    M5_QUESTIONS_PROMPT_CLASSIFICATION,
)
from case_generator.prompts.clasificacion.narrative import (
    M4_PROMPT_CLASSIFICATION,
    M5_PROMPT_CLASSIFICATION,
)
from case_generator.prompts.clasificacion.notebook import (
    M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION,
)
from case_generator.prompts.clasificacion.notebooks import (
    CLASSIFICATION_NOTEBOOK_PROMPT_BY_VARIANT,
    CLASSIFICATION_NOTEBOOK_VARIANT_LR_ONLY,
    CLASSIFICATION_NOTEBOOK_VARIANT_LR_RF_CONTRAST,
    CLASSIFICATION_NOTEBOOK_VARIANT_RF_ONLY,
    ClassificationNotebookVariant,
    M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_LR_ONLY,
    M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_LR_RF_CONTRAST,
    M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_RF_ONLY,
    TOC_MARKDOWN_CELL_BY_VARIANT,
)

__all__ = [
    "CASE_ARCHITECT_PROMPT_CLASSIFICATION",
    "M1_CLASSIFICATION_BUSINESS_TARGET_BLOCK",
    "CASE_WRITER_PROMPT_CLASSIFICATION",
    "CASE_QUESTIONS_PROMPT_CLASSIFICATION",
    "build_cost_matrix_block",
    "EDA_ANNOTATE_ONLY_PROMPT_CLASSIFICATION",
    "EDA_QUESTIONS_GENERATOR_PROMPT_CLASSIFICATION",
    "EDA_TEXT_ANALYST_PROMPT_CLASSIFICATION",
    "SCHEMA_DESIGNER_PROMPT_CLASSIFICATION",
    "select_eda_text_blocks",
    "M3_CONTENT_PROMPT_CLASSIFICATION",
    "M3_CONTENT_PROMPT_CLASSIFICATION_LR_ONLY",
    "M3_CONTENT_PROMPT_CLASSIFICATION_RF_ONLY",
    "M3_CONTENT_PROMPT_CLASSIFICATION_BY_VARIANT",
    "M3_CLASSIFICATION_QUESTIONS_PROMPT_LR_ONLY",
    "M3_CLASSIFICATION_QUESTIONS_PROMPT_RF_ONLY",
    "M3_CLASSIFICATION_QUESTIONS_PROMPT_LR_RF_CONTRAST",
    "M3_CLASSIFICATION_QUESTIONS_BY_VARIANT",
    "M3_NOTEBOOK_QUESTIONS_PROMPT_CLASSIFICATION_LR_ONLY",
    "M3_NOTEBOOK_QUESTIONS_PROMPT_CLASSIFICATION_RF_ONLY",
    "M3_NOTEBOOK_QUESTIONS_PROMPT_CLASSIFICATION_BY_VARIANT",
    "M4_NARRATIVE_PROMPT_CLASSIFICATION",
    "M4_NARRATIVE_PROMPT_CLASSIFICATION_LR_ONLY",
    "M4_NARRATIVE_PROMPT_CLASSIFICATION_RF_ONLY",
    "M4_NARRATIVE_PROMPT_CLASSIFICATION_BY_VARIANT",
    "M4_QUESTIONS_PROMPT_CLASSIFICATION",
    "M4_CHART_PROMPT_CLASSIFICATION",
    "M4_CHART_PROMPT_CLASSIFICATION_LEGACY",
    "M4_PROMPT_CLASSIFICATION",
    "M5_NARRATIVE_PROMPT_CLASSIFICATION",
    "M5_NARRATIVE_PROMPT_CLASSIFICATION_LR_ONLY",
    "M5_NARRATIVE_PROMPT_CLASSIFICATION_RF_ONLY",
    "M5_NARRATIVE_PROMPT_CLASSIFICATION_BY_VARIANT",
    "M5_QUESTIONS_PROMPT_CLASSIFICATION",
    "M5_PROMPT_CLASSIFICATION",
    "M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION",
    "M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_LR_ONLY",
    "M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_RF_ONLY",
    "M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_LR_RF_CONTRAST",
    "CLASSIFICATION_NOTEBOOK_PROMPT_BY_VARIANT",
    "CLASSIFICATION_NOTEBOOK_VARIANT_LR_ONLY",
    "CLASSIFICATION_NOTEBOOK_VARIANT_RF_ONLY",
    "CLASSIFICATION_NOTEBOOK_VARIANT_LR_RF_CONTRAST",
    "ClassificationNotebookVariant",
    "TOC_MARKDOWN_CELL_BY_VARIANT",
]
