"""Classification M3 notebook prompt variants."""

from case_generator.prompts.clasificacion.notebooks._shared import (
    CLASSIFICATION_NOTEBOOK_VARIANT_LR_ONLY,
    CLASSIFICATION_NOTEBOOK_VARIANT_LR_RF_CONTRAST,
    CLASSIFICATION_NOTEBOOK_VARIANT_RF_ONLY,
    ClassificationNotebookVariant,
)
from case_generator.prompts.clasificacion.notebooks.contrast import (
    M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_LR_RF_CONTRAST,
)
from case_generator.prompts.clasificacion.notebooks.logistic_regression import (
    M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_LR_ONLY,
)
from case_generator.prompts.clasificacion.notebooks.random_forest import (
    M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_RF_ONLY,
)


CLASSIFICATION_NOTEBOOK_PROMPT_BY_VARIANT: dict[
    ClassificationNotebookVariant,
    str,
] = {
    CLASSIFICATION_NOTEBOOK_VARIANT_LR_ONLY: M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_LR_ONLY,
    CLASSIFICATION_NOTEBOOK_VARIANT_RF_ONLY: M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_RF_ONLY,
    CLASSIFICATION_NOTEBOOK_VARIANT_LR_RF_CONTRAST: M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_LR_RF_CONTRAST,
}


__all__ = [
    "CLASSIFICATION_NOTEBOOK_PROMPT_BY_VARIANT",
    "CLASSIFICATION_NOTEBOOK_VARIANT_LR_ONLY",
    "CLASSIFICATION_NOTEBOOK_VARIANT_LR_RF_CONTRAST",
    "CLASSIFICATION_NOTEBOOK_VARIANT_RF_ONLY",
    "ClassificationNotebookVariant",
    "M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_LR_ONLY",
    "M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_LR_RF_CONTRAST",
    "M3_NOTEBOOK_ALGO_PROMPT_CLASSIFICATION_RF_ONLY",
]
