"""Phase5_canonical_output_column

Revision ID: 1571dcf87c69
Revises: 6185b1d0f91e
Create Date: 2026-03-13 13:34:43.546717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1571dcf87c69'
down_revision: Union[str, Sequence[str], None] = '6185b1d0f91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('canonical_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'canonical_output')
    # ### end Alembic commands ###

