"""phase4a_runtime_models

Revision ID: 6185b1d0f91e
Revises: fab7ddd36c0c
Create Date: 2026-03-12 22:42:44.884826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6185b1d0f91e'
down_revision: Union[str, Sequence[str], None] = 'fab7ddd36c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'assignment_id', name='uix_student_assignment')
    )
    op.create_table('module_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_assignment_id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_assignment_id'], ['student_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_thread_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('module_attempt_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('twin_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_attempt_id'], ['module_attempts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_table('grading_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('module_attempt_id', sa.String(length=36), nullable=False),
    sa.Column('layer_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_module_score', sa.Float(), nullable=False),
    sa.Column('grader_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_attempt_id'], ['module_attempts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_attempt_id', name='uix_grading_result_attempt')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grading_results')
    op.drop_table('chat_thread_index')
    op.drop_table('module_attempts')
    op.drop_table('student_assignments')
    # ### end Alembic commands ###

