"""issue_205_case_grades

Revision ID: 9ee3b0659e9a
Revises: c1964e5f6a7b
Create Date: 2026-04-25 22:41:24.513131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '9ee3b0659e9a'
down_revision: Union[str, Sequence[str], None] = 'c1964e5f6a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_grades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('membership_id', sa.Text(), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), server_default=sa.text('5.00'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graded_by_membership_id', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('in_progress', 'submitted', 'graded')", name='ck_case_grades_status'),
    sa.CheckConstraint('max_score > 0', name='ck_case_grades_max_score_positive'),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= max_score)', name='ck_case_grades_score_range'),
    sa.CheckConstraint(
        "((status = 'graded' AND score IS NOT NULL AND graded_at IS NOT NULL) OR "
        "(status IN ('in_progress', 'submitted') AND score IS NULL AND graded_at IS NULL))",
        name='ck_case_grades_state_consistency',
    ),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graded_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'assignment_id', name='uix_case_grades_membership_assignment')
    )
    op.create_index('ix_case_grades_course_assignment', 'case_grades', ['course_id', 'assignment_id'], unique=False)
    op.create_index('ix_case_grades_course_membership', 'case_grades', ['course_id', 'membership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_case_grades_course_membership', table_name='case_grades')
    op.drop_index('ix_case_grades_course_assignment', table_name='case_grades')
    op.drop_table('case_grades')
    # ### end Alembic commands ###
