"""Add ArtifactManifest idempotency

Revision ID: fab7ddd36c0c
Revises: 26812dc7bf5c
Create Date: 2026-03-10 14:36:46.715989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab7ddd36c0c'
down_revision: Union[str, Sequence[str], None] = '26812dc7bf5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifact_manifests', sa.Column('job_id', sa.String(length=36), nullable=False))
    op.add_column('artifact_manifests', sa.Column('producer_node', sa.String(length=100), nullable=False))
    op.create_unique_constraint('uix_artifact_manifest_idempotency', 'artifact_manifests', ['assignment_id', 'job_id', 'artifact_type', 'producer_node'])
    op.create_foreign_key(None, 'artifact_manifests', 'authoring_jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artifact_manifests', type_='foreignkey')
    op.drop_constraint('uix_artifact_manifest_idempotency', 'artifact_manifests', type_='unique')
    op.drop_column('artifact_manifests', 'producer_node')
    op.drop_column('artifact_manifests', 'job_id')
    # ### end Alembic commands ###

